// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStore_backend.Data;

#nullable disable

namespace MyStore_backend.Migrations.MyStoreProductsDB
{
    [DbContext(typeof(MyStoreProductsDBContext))]
    [Migration("20250628203027_updateProductSeedData")]
    partial class updateProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("MyStore_backend.Models.Domain.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Quantity = 2,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Quantity = 1,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Quantity = 1,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Quantity = 3,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Quantity = 2,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Quantity = 1,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Quantity = 2,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Quantity = 2,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Quantity = 1,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5"),
                            ProductId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Quantity = 3,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("MyStore_backend.Models.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Category = "T-Shirt",
                            Description = "Experience timeless style and comfort with our Premium Classic White T-Shirt. Crafted from high-quality, breathable cotton, this versatile piece is perfect for any occasion, whether you're dressing up or keeping it casual. Its tailored fit and soft fabric ensure all-day comfort, making it a staple in any modern wardrobe.",
                            ImageUrl = "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=400&q=80",
                            Name = "Premium Classic White T-Shirt",
                            Price = 29.99m,
                            Stock = 99
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Category = "Jeans",
                            Description = "Our Signature Blue Denim Jeans offer a classic look with a modern twist. Made from durable, premium denim, these jeans provide a comfortable fit and exceptional longevity. The timeless blue wash and expert tailoring make them suitable for both casual outings and more formal settings, ensuring you always look your best.",
                            ImageUrl = "https://vilapuuvilla.fi/cdn/shop/products/0520bad2-dc50-40ae-9f90-afce00862eff_14094341_4429742_001_preview.jpg?v=1701160840",
                            Name = "Signature Blue Denim Jeans",
                            Price = 59.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Category = "Shoes",
                            Description = "Achieve your fitness goals with our Elite Performance Running Sneakers. Engineered for maximum comfort and support, these sneakers feature advanced cushioning technology and a lightweight, breathable design. Perfect for both daily runs and casual wear, they deliver superior traction and durability for any activity.",
                            ImageUrl = "https://pyxis.nymag.com/v1/imgs/a6d/fc0/4da4be21d1741718404660586a5b6a6f3e.jpg",
                            Name = "Elite Performance Running Sneakers",
                            Price = 89.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Category = "Accessories",
                            Description = "Keep your essentials organized in style with our Luxury Brown Leather Wallet. Handcrafted from premium genuine leather, this wallet features multiple card slots, a spacious bill compartment, and a sleek, elegant design. Its rich brown color and fine stitching make it a sophisticated accessory for any professional.",
                            ImageUrl = "https://m.media-amazon.com/images/I/81WIcyHQ7oL._AC_UY1100_.jpg",
                            Name = "Luxury Brown Leather Wallet",
                            Price = 39.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Category = "Hats",
                            Description = "Add a pop of color to your outfit with our Adjustable Red Baseball Cap. Designed for comfort and style, this cap features a customizable fit, breathable fabric, and a classic curved brim. Ideal for outdoor activities or casual wear, it offers both sun protection and a fashionable look.",
                            ImageUrl = "https://store.moma.org/cdn/shop/files/3a2b0b12-bde3-4a63-bba2-b561dbd7de29_5fa67989-c4a0-4bea-a74b-fb25ed894895.jpg?v=1710971142",
                            Name = "Adjustable Red Baseball Cap",
                            Price = 19.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Category = "T-Shirt",
                            Description = "Showcase your playful side with our Artisan Cat Graphic White T-Shirt. Made from ultra-soft cotton, this shirt features a unique, artist-designed cat graphic that adds personality to your wardrobe. Its comfortable fit and eye-catching design make it perfect for both casual outings and relaxed weekends.",
                            ImageUrl = "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8VCUyMHNoaXJ0fGVufDB8fDB8fHww",
                            Name = "Artisan Cat Graphic White T-Shirt",
                            Price = 29.99m,
                            Stock = 99
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Category = "T-Shirt",
                            Description = "Express your creativity with our Modern Art Text Black T-Shirt. This premium tee features a bold, artistic text design on high-quality black fabric. Its contemporary style and comfortable fit make it a standout piece for anyone looking to make a statement while enjoying all-day comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fFQlMjBzaGlydHxlbnwwfHwwfHx8MA%3D%3D",
                            Name = "Modern Art Text Black T-Shirt",
                            Price = 15.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Category = "T-Shirt",
                            Description = "Elevate your everyday look with our Minimalist Logo White T-Shirt. Featuring a subtle 'b' logo, this shirt is crafted from soft, breathable fabric for maximum comfort. Its clean design and modern aesthetic make it a versatile addition to any wardrobe, suitable for both casual and semi-formal occasions.",
                            ImageUrl = "https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Minimalist Logo White T-Shirt",
                            Price = 18.50m,
                            Stock = 200
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Category = "T-Shirt",
                            Description = "Make a bold impression with our TAY SON Text Black T-Shirt. This shirt features a striking 'TAY SON' print on premium black fabric, offering both comfort and style. Its modern fit and durable material make it ideal for daily wear, while the unique design sets you apart from the crowd.",
                            ImageUrl = "https://images.unsplash.com/photo-1627225925683-1da7021732ea?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "TAY SON Text Black T-Shirt",
                            Price = 18.50m,
                            Stock = 200
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Category = "T-Shirt",
                            Description = "Stand out with our Skeleton Hand Graphic Black T-Shirt. Featuring a detailed graphic of a hand skeleton, this shirt is made from high-quality fabric for lasting comfort. Its edgy design and modern fit make it a perfect choice for those who appreciate unique, artistic apparel.",
                            ImageUrl = "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjZ8fFQlMjBzaGlydHxlbnwwfHwwfHx8MA%3D%3D",
                            Name = "Skeleton Hand Graphic Black T-Shirt",
                            Price = 28.50m,
                            Stock = 200
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Category = "Accessories",
                            Description = "Add a touch of sophistication to your ensemble with our Elegant Silver Necklace. Expertly crafted with a timeless design, this necklace complements both casual and formal attire. Its high-quality materials ensure durability and shine, making it a cherished accessory for years to come.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1681276170423-2c60b95094b4?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Elegant Silver Necklace",
                            Price = 50.50m,
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Category = "Accessories",
                            Description = "Stay stylish and protected from the sun with our Chic Straw Sun Hat. This fashionable accessory is woven from high-quality straw, offering both durability and breathability. Its elegant design makes it perfect for beach outings, garden parties, or any sunny day adventure.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1693221161784-e6a735e8e4b4?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Chic Straw Sun Hat",
                            Price = 30.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Category = "Shoes",
                            Description = "Step up your game with our Red Nike Athletic Shoes. Designed for both performance and style, these shoes feature advanced cushioning, a supportive fit, and a vibrant red color. Ideal for sports, workouts, or everyday wear, they provide the comfort and durability you expect from Nike.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Red Nike Athletic Shoes",
                            Price = 70.00m,
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Category = "Jeans",
                            Description = "Discover timeless fashion with our Women's Classic Blue Jeans. Expertly tailored for a flattering fit, these jeans are made from premium denim that offers both comfort and durability. The classic blue wash and versatile design make them a must-have for any wardrobe, suitable for any occasion.",
                            ImageUrl = "https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Women's Classic Blue Jeans",
                            Price = 20.00m,
                            Stock = 99
                        });
                });

            modelBuilder.Entity("MyStore_backend.Models.Domain.CartItem", b =>
                {
                    b.HasOne("MyStore_backend.Models.Domain.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyStore_backend.Models.Domain.Product", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
